import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { UserCheck, UserMinus, Users, ShieldCheck, Download, ChevronDown, History, Activity, TrendingUp, Skull, MapPin } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { cn } from '@/lib/utils';
import type { AuditData, RelationDetail } from '@/lib/db';

interface AuditReportProps {
  data: AuditData;
  onAudit: (name: string, context?: string) => void;
}

export function AuditReport({ data, onAudit }: AuditReportProps) {
  const handleExport = () => {
    const formatRelation = (items: RelationDetail[]) => {
      if (items.length === 0) return '_No data found_';
      return items.map(item => {
        let text = `### ${item.name}`;
        if (item.isDeceased) {
          text += ` (Deceased${item.causeOfDeath ? `: ${item.causeOfDeath}` : ''})`;
        }
        text += `\n- **Past:** ${item.past}\n- **Present:** ${item.present}\n- **Future:** ${item.future}`;
        return text;
      }).join('\n\n');
    };

    const markdownContent = `
# Character Audit: ${data.name}

## Executive Summary
${data.summary}

${data.whereabouts ? `## Current Whereabouts\n${data.whereabouts}\n` : ''}
## Allies & Friends
${formatRelation(data.friends)}

## Known Associates
${formatRelation(data.associates)}

## Rivals & Enemies
${formatRelation(data.enemies)}

## Verified Sources
${data.sources && data.sources.length > 0 ? data.sources.map(source => `- [${source.title || new URL(source.uri).hostname}](${source.uri})`).join('\n') : '_No sources listed_'}

---
*Generated by Character Audit Protocol*
    `.trim();

    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.name.replace(/\s+/g, '_')}_audit.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.3, delay: 0.1 }}
      className="w-full max-w-6xl mx-auto space-y-8"
    >
      {/* Header */}
      <div className="text-center space-y-4 mb-12 relative">
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-zinc-100 dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-800 text-xs font-mono text-zinc-600 dark:text-zinc-400 uppercase tracking-wider"
        >
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
          Audit Complete
        </motion.div>
        
        <div className="absolute right-0 top-0 hidden md:block">
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-zinc-100 dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-800 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white hover:border-zinc-400 dark:hover:border-zinc-700 transition-all text-sm font-medium"
          >
            <Download className="w-4 h-4" />
            Export Report
          </button>
        </div>

        <h2 className="text-4xl md:text-6xl font-bold tracking-tight text-zinc-900 dark:text-white">
          {data.name}
        </h2>
        <div className="h-px w-24 bg-gradient-to-r from-transparent via-zinc-400 dark:via-zinc-500 to-transparent mx-auto" />
        
        <div className="md:hidden flex justify-center mt-4">
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-zinc-100 dark:bg-zinc-900 border border-zinc-300 dark:border-zinc-800 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white hover:border-zinc-400 dark:hover:border-zinc-700 transition-all text-sm font-medium"
          >
            <Download className="w-4 h-4" />
            Export Report
          </button>
        </div>
      </div>

      {/* Executive Summary */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15, duration: 0.3 }}
        className="bg-white/80 dark:bg-zinc-900/50 backdrop-blur-sm border border-zinc-300 dark:border-white/10 rounded-3xl p-8 md:p-10 shadow-2xl relative overflow-hidden group"
      >
        <div className="absolute top-0 right-0 p-6 opacity-5 dark:opacity-10 group-hover:opacity-10 dark:group-hover:opacity-20 transition-opacity">
          <ShieldCheck className="w-32 h-32 text-zinc-900 dark:text-white" />
        </div>
        <h3 className="text-xl font-mono text-zinc-600 dark:text-zinc-400 mb-6 flex items-center gap-3">
          <span className="w-8 h-px bg-zinc-400 dark:bg-zinc-600" />
          EXECUTIVE SUMMARY
        </h3>
        <div className="prose dark:prose-invert prose-lg max-w-none text-zinc-700 dark:text-zinc-300 leading-relaxed">
          <ReactMarkdown>{data.summary}</ReactMarkdown>
        </div>
      </motion.div>

      {/* Current Whereabouts */}
      {data.whereabouts && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.17, duration: 0.3 }}
          className="bg-gradient-to-br from-emerald-50/80 to-sky-50/80 dark:from-emerald-950/20 dark:to-sky-950/20 backdrop-blur-sm border border-emerald-200 dark:border-emerald-900/30 rounded-2xl p-6 md:p-8 shadow-xl relative overflow-hidden group"
        >
          <div className="absolute top-0 right-0 p-6 opacity-5 dark:opacity-10 group-hover:opacity-10 dark:group-hover:opacity-20 transition-opacity">
            <MapPin className="w-24 h-24 text-emerald-600 dark:text-emerald-400" />
          </div>
          <h3 className="text-lg font-mono text-emerald-700 dark:text-emerald-400 mb-4 flex items-center gap-3">
            <MapPin className="w-5 h-5" />
            CURRENT WHEREABOUTS
          </h3>
          <div className="prose dark:prose-invert max-w-none text-zinc-700 dark:text-zinc-300 leading-relaxed">
            <ReactMarkdown>{data.whereabouts}</ReactMarkdown>
          </div>
        </motion.div>
      )}

      {/* Network Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <NetworkColumn
          title="Allies & Friends"
          items={data.friends}
          icon={UserCheck}
          color="emerald"
          delay={0.2}
          onAudit={(name, context) => onAudit(name, `${context} ${data.name}`)}
        />

        <NetworkColumn
          title="Known Associates"
          items={data.associates}
          icon={Users}
          color="blue"
          delay={0.25}
          onAudit={(name, context) => onAudit(name, `${context} ${data.name}`)}
        />

        <NetworkColumn
          title="Rivals & Enemies"
          items={data.enemies}
          icon={UserMinus}
          color="rose"
          delay={0.3}
          onAudit={(name, context) => onAudit(name, `${context} ${data.name}`)}
        />
      </div>

      {/* Sources */}
      {data.sources && data.sources.length > 0 && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4, duration: 0.3 }}
          className="pt-8 border-t border-zinc-200 dark:border-white/5"
        >
          <h4 className="text-sm font-mono text-zinc-500 dark:text-zinc-500 mb-4 uppercase tracking-wider">Verified Sources</h4>
          <div className="flex flex-wrap gap-3">
            {data.sources.map((source, i) => (
              <a
                key={i}
                href={source.uri}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs text-zinc-600 dark:text-zinc-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors bg-zinc-100 dark:bg-zinc-900/50 px-3 py-1.5 rounded-lg border border-zinc-300 dark:border-white/5 hover:border-emerald-500/50 dark:hover:border-emerald-500/30 truncate max-w-[200px]"
              >
                {source.title || new URL(source.uri).hostname}
              </a>
            ))}
          </div>
        </motion.div>
      )}
    </motion.div>
  );
}

function NetworkColumn({ title, items, icon: Icon, color, delay, onAudit }: { title: string, items: RelationDetail[], icon: any, color: 'emerald' | 'blue' | 'rose', delay: number, onAudit: (name: string, context?: string) => void }) {
  const colors = {
    emerald: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
    blue: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    rose: "text-rose-400 bg-rose-500/10 border-rose-500/20",
  };

  const getContext = () => {
    if (color === 'emerald') return 'Friend of';
    if (color === 'blue') return 'Associate of';
    if (color === 'rose') return 'Rival of';
    return 'Associate of';
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay, duration: 0.3 }}
      className="bg-white/60 dark:bg-zinc-900/30 backdrop-blur-sm border border-zinc-300 dark:border-white/5 rounded-2xl p-6 flex flex-col h-full shadow-lg"
    >
      <div className="flex items-center gap-3 mb-6">
        <div className={cn("p-2.5 rounded-xl", colors[color])}>
          <Icon className="w-5 h-5" />
        </div>
        <h3 className="font-semibold text-zinc-900 dark:text-zinc-200">{title}</h3>
      </div>
      
      {items.length > 0 ? (
        <div className="space-y-3 flex-1">
          {items.map((item, i) => (
            <PersonCard 
              key={i} 
              item={item} 
              color={color} 
              delay={delay + (i * 0.03)} 
              onAudit={(name) => onAudit(name, getContext())}
            />
          ))}
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center text-zinc-400 dark:text-zinc-600 text-sm italic py-8">
          No data found
        </div>
      )}
    </motion.div>
  );
}

function PersonCard({ item, color, delay, onAudit }: { item: RelationDetail, color: 'emerald' | 'blue' | 'rose', delay: number, onAudit: (name: string) => void }) {
  const [isExpanded, setIsExpanded] = useState(false);

  const dotColors = {
    emerald: "bg-emerald-500",
    blue: "bg-blue-500",
    rose: "bg-rose-500",
  };

  const borderColors = {
    emerald: "group-hover:border-emerald-500/30",
    blue: "group-hover:border-blue-500/30",
    rose: "group-hover:border-rose-500/30",
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay, duration: 0.2 }}
      onClick={() => setIsExpanded(!isExpanded)}
      className={cn(
        "group relative bg-white dark:bg-zinc-900/40 hover:bg-zinc-50 dark:hover:bg-zinc-800/60 rounded-xl border border-zinc-200 dark:border-white/5 transition-colors duration-200 cursor-pointer overflow-hidden shadow-sm",
        borderColors[color],
        isExpanded ? "ring-1 ring-zinc-300 dark:ring-white/10 bg-zinc-50 dark:bg-zinc-800/40" : ""
      )}
    >
      <div className="p-4 flex items-start justify-between gap-3">
        <div className="flex items-center gap-3 flex-1 min-w-0">
          <span className={cn("w-2 h-2 rounded-full flex-shrink-0", dotColors[color])} />
          <div className="flex flex-col min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-medium text-zinc-900 dark:text-zinc-200 leading-relaxed">{item.name}</span>
              {item.isDeceased && (
                <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-zinc-200 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-400 border border-zinc-300 dark:border-zinc-700 flex-shrink-0">
                  <Skull className="w-3 h-3" />
                  Deceased
                </span>
              )}
            </div>
            {item.isDeceased && item.causeOfDeath && (
               <span className="text-[10px] text-zinc-500 dark:text-zinc-500 italic">Cause: {item.causeOfDeath}</span>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <button
            onClick={(e) => {
              e.stopPropagation();
              onAudit(item.name);
            }}
            className="p-1.5 rounded-lg bg-zinc-100 dark:bg-zinc-800/50 hover:bg-emerald-100 dark:hover:bg-emerald-500/20 text-zinc-600 dark:text-zinc-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors border border-zinc-200 dark:border-transparent hover:border-emerald-400 dark:hover:border-emerald-500/30"
            title={`Audit ${item.name}`}
          >
            <ShieldCheck className="w-4 h-4" />
          </button>
          <ChevronDown 
            className={cn(
              "w-4 h-4 text-zinc-400 dark:text-zinc-500 transition-transform duration-200",
              isExpanded ? "rotate-180 text-zinc-700 dark:text-zinc-300" : "group-hover:text-zinc-600 dark:group-hover:text-zinc-400"
            )} 
          />
        </div>
      </div>

      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4">
              <div className="relative pl-4 space-y-6 border-l border-zinc-200 dark:border-white/10 ml-1">
                {/* Past */}
                <div className="relative">
                  <div className="absolute -left-[21px] top-1 w-2.5 h-2.5 rounded-full bg-zinc-200 dark:bg-zinc-800 border border-zinc-400 dark:border-zinc-600" />
                  <div className="flex items-center gap-2 mb-1 text-zinc-500 dark:text-zinc-500 text-xs font-mono uppercase tracking-wider">
                    <History className="w-3 h-3" />
                    Past
                  </div>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">{item.past}</p>
                </div>

                {/* Present */}
                <div className="relative">
                  <div className={cn("absolute -left-[21px] top-1 w-2.5 h-2.5 rounded-full border", dotColors[color], "border-transparent shadow-[0_0_8px_rgba(0,0,0,0.5)]")} />
                  <div className="flex items-center gap-2 mb-1 text-zinc-800 dark:text-zinc-200 text-xs font-mono uppercase tracking-wider font-semibold">
                    <Activity className="w-3 h-3" />
                    Present
                  </div>
                  <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed">{item.present}</p>
                </div>

                {/* Future */}
                <div className="relative">
                  <div className="absolute -left-[21px] top-1 w-2.5 h-2.5 rounded-full bg-zinc-200 dark:bg-zinc-800 border border-zinc-400 dark:border-zinc-600" />
                  <div className="flex items-center gap-2 mb-1 text-zinc-500 dark:text-zinc-500 text-xs font-mono uppercase tracking-wider">
                    <TrendingUp className="w-3 h-3" />
                    Future
                  </div>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed italic">{item.future}</p>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      
      {!isExpanded && (
        <div className="px-4 pb-4 pt-0">
          <p className="text-xs text-zinc-600 dark:text-zinc-500 line-clamp-2 pl-5 border-l border-zinc-200 dark:border-white/5 ml-1">
            {item.present}
          </p>
        </div>
      )}
    </motion.div>
  );
}
